version: '3.7'

services:
    dhu:
        build:
          context: .
        image: grachev/dhu
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./:/usr/local/app

    nginx:
        image: nginx:alpine
        labels:
            ru.grachevko.dhu: '{www,api,img,admin,profile}.nginx.local'

    nginx2:
        image: nginx:alpine
        labels:
            ru.grachevko.dhu: '{www,admin,api}.nginx.local:2'

    nginx3:
        image: nginx:alpine
        labels:
            ru.grachevko.dhu: 'img.nginx.local:3;api.nginx.local:5'
